Vagrant.configure("2") do |config|
  config.ssh.username = "vagrant"

  config.ssh.keep_alive = true

  config.vm.box = "debian/bullseye64"
  config.vm.boot_timeout = 600

  config.vm.provision "shell", inline: 'apt-get update && apt-get install --yes mininet iperf3 iperf gcc cmake linux-headers-"$(uname -r)"'

  config.vm.provision "shell", inline: 'sudo modprobe mpls_iptunnel'

  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "../../../src/", "/home/vagrant/ti-mfa-src"

end
