Vagrant.configure("2") do |config|
  # ssh configuration
  config.ssh.username = "vagrant"

  config.ssh.keep_alive = true

  config.vm.box = "debian/bullseye64"
  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = "512"
    virtualbox.cpus = "1"
  end

  config.vm.provision "shell", inline: "apt-get install --yes python3-apt"
  config.vm.synced_folder "../../src", "/home/vagrant/ti-mfa-src"

  # Network topology
  # see https://www.univie.ac.at/ct/stefan/gi18.pdf figure 1
  #
  #                                           Router 1
  #                                         10.200.200.1
  #                                           +-------+
  #                                           |       |
  #      +------------------------------------|   t   |------------------------------------+
  #  e_l |                      192.168.12.11 |       | 192.168.14.11                      |
  #      |                                    +-------+                                e_r |
  #      |                          192.168.13.11 |                                        |
  #      |                                    e_m |                                        |
  #      |                                        |                                        |
  #      |                                        |                                        |
  #      |                                        |                                        |
  #      |                                        |                                        |
  #      | 192.168.12.12                          | 192.168.13.13            192.168.14.14 |
  #  +-------+                                +-------+                                +-------+
  #  |       |               l-to-m           |       |               m-to-r           |       |
  #  |  v_l  |--------------------------------|  v_m  |--------------------------------|  v_r  |
  #  |       | 192.168.23.12    192.168.23.13 |       | 192.168.34.13    192.168.34.14 |       |
  #  +-------+                                +-------+                                +-------+
  #  10.200.200.2                            10.200.200.3                             10.200.200.4
  #  Router 2                                 Router 3                                 Router 4

  PRIVATE_NETWORK_PREFIX = "192.168"
  VM_NETWORK_CONFIG = {
    "t": {
      "e_l": "12.11",
      "e_m": "13.11",
      "e_r": "14.11"
    },
    "v-l": {
      "e_l": "12.12",
      "l-to-m": "23.12"
    },
    "v-m": {
      "l-to-m": "23.13",
      "e_m": "13.13",
      "m-to-r": "34.13"
    },
    "v-r": {
      "m-to-r": "34.14",
      "e_r": "14.14"
    }
  }

  enabled_igp = ENV['ENABLED_IGP']

  enabled_igp = "ospf" if enabled_igp == nil

  VM_NETWORK_CONFIG.each_with_index do |(machine_id, network_config), index|
    config.vm.define "timfa-test-machine-#{machine_id}" do |machine|
      machine.vm.hostname = "timfa-test-machine-#{machine_id}"

      network_config.each do |network_name, ip_address_suffix|
        machine.vm.network "private_network",
          ip: "#{PRIVATE_NETWORK_PREFIX}.#{ip_address_suffix}",
          virtualbox__intnet: "#{network_name}"
      end

      machine.vm.provision :ansible do |ansible|
        ansible.extra_vars = {
          loopback_ipv4_address: "10.200.200.#{index + 1}",
          enable_isis: enabled_igp.downcase == "isis",
          enable_ospf: enabled_igp.downcase == "ospf"
        }
        ansible.verbose = "v"
        ansible.playbook = "common.yml"
      end
    end
  end
end
