Vagrant.configure("2") do |config|
  config.ssh.username = "vagrant"
  config.ssh.keep_alive = true

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.box = "debian/testing64"
  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = "512"
    virtualbox.cpus = "1"
  end

  config.vm.provision "shell", inline: "apt-get install --yes python3-apt"
  config.vm.provision :ansible do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "build.yml"
  end
end
