Vagrant.configure("2") do |config|
  config.ssh.username = "vagrant"

  config.ssh.keep_alive = true

  config.vm.box = "debian/testing64"
  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = "512"
    virtualbox.cpus = "1"
  end

  config.vm.provision "shell", inline: "apt-get update && apt-get install gcc cmake linux-image-amd64 linux-headers-amd64 --yes"

  config.vm.synced_folder "." "/vagrant", disabled: true
  config.vm.provision "file", source: "../../src/", destination: "/home/vagrant/ti-mfa-src"

end
