---
name: build

on: push

jobs:
  build:
    # Only macos has vagrant and virtual box installed
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        id: vagrant-base-box-cache
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('tests/unit/Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Build vagrant box && Restart for new kernel
        working-directory: tests/unit
        run: vagrant up && vagrant reload

      - name: Compile code
        working-directory: tests/unit
        run: vagrant ssh -c "cd ti-mfa-src && make all"
